#!/usr/bin/env python

import argparse
import csv



# print a line with information for the user
def print_info(message):
    print("[INFO] " + message)



# print an error line to the user
def die(message):
    print("[ERROR] " + message)



# check what arguments the user gave to Willy
def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", help="Tell Willy what to do.")
    parser.add_argument("file",
                        help="Tell Willy what file to do something with.")
    parser.add_argument("-o", "--output-file",
                        help="Tell Willy what file to write to.")

    args = parser.parse_args()

    return args



# the dropCrap command. It throws away all data fields except for "IKL",
# "TRACE_ID", and "TYPE_OMSCHRIJVING"
def drop_crap(args):
    #load data file
    print_info("I'm loading your file. Be patient, it's 19 million records and I don't know how to multithread.")

    #create a new file to write to
    path = "willyWroteThis.txt"
    if args.output_file:
        path = args.output_file

    #process data and print to new file
    with open(args.file, "r") as read_file:
        with open(path, "w") as write_file:
            reader = csv.reader(read_file, delimiter=';')
            for row in reader:
                write_file.write(row[0] + "," + row[2] + "," + row[4] + "\n")

    print_info("Yo dude, I put all that good stuff you asked for in " + path)




################################################################################
## Program Start
################################################################################

if __name__ == "__main__":
    args = parse_arguments()


    # start the dropCrap command
    if args.command == "dropCrap":
        drop_crap(args)


    # execute this is the command was unknown
    else:
        die("Yo man, what is this '" + args.command +
                "' thing you're talking about? I don't know how to do that.")
